name = "InvertedFiles"
uuid = "b20bd276-2c70-11ec-161a-3d1e1109a1c3"
authors = ["Eric S. Tellez <donsadit@gmail.com> and contributors"]
version = "0.1.4"

[deps]
Intersections = "6d0fbc77-481e-44fe-9ace-1653ddcdea34"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Intersections = "0.2"
SimilaritySearch = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
